// Realistic mock data for the AI-powered reporting dashboard.
// Shapes here mirror what we expect the backend to eventually return.

export const REPORT_CATEGORIES = [
  'Infrastructure',
  'Health',
  'Environment',
  'Security',
  'Logistics',
  'Utilities',
  'Other',
];

export const SEVERITY_LEVELS = ['low', 'medium', 'high', 'critical'];

// --- Mock AI insights ----------------------------------------------------

export const mockInsights = {
  summary:
    'Brief 1–2 sentence human-readable summary generated by the AI from the report content.',
  category: 'Infrastructure',
  severity: 'high',
  sentiment: 'negative',
  confidence: 0.87,
  keywords: ['power outage', 'transformer', 'block B', 'low voltage'],
  entities: {
    locations: ['Block B', 'Sector 4'],
    people: [],
    organizations: ['City Power Utility'],
  },
  recommendations: [
    'Dispatch field crew to Block B substation.',
    'Notify Sector 4 residents via SMS.',
    'Schedule transformer inspection within 24h.',
  ],
};

// --- Mock reports list ---------------------------------------------------

const SAMPLE_REPORTS = [
  {
    id: 'RPT-1001',
    title: 'Power outage in Block B substation',
    description:
      'Since 06:40 this morning the entire Block B section has been without power. Voltage dropped sharply before the outage. Multiple households are reporting spoilage of refrigerated goods.',
    category: 'Infrastructure',
    severity: 'high',
    status: 'in_review',
    location: 'Block B, Sector 4',
    hasImage: true,
    imageUrl: null,
    submittedBy: 'Asma Rahman',
    submittedAt: '2026-06-29T06:55:00Z',
    ai: {
      summary:
        'Confirmed wide-area power outage affecting Block B starting 06:40. Likely transformer fault based on reported pre-outage voltage drop.',
      category: 'Infrastructure',
      severity: 'high',
      sentiment: 'negative',
      confidence: 0.91,
      keywords: ['power outage', 'transformer', 'Block B', 'low voltage'],
      entities: {
        locations: ['Block B', 'Sector 4'],
        people: [],
        organizations: ['City Power Utility'],
      },
      recommendations: [
        'Dispatch field crew to Block B substation.',
        'Notify Sector 4 residents via SMS.',
        'Schedule transformer inspection within 24h.',
      ],
    },
  },
  {
    id: 'RPT-1002',
    title: 'Suspected dengue cluster in Sector 7',
    description:
      'Three households on Lane 9 have reported fever with rash symptoms within 48 hours. Standing water observed in the open drain behind the row.',
    category: 'Health',
    severity: 'critical',
    status: 'action_required',
    location: 'Sector 7, Lane 9',
    hasImage: true,
    imageUrl: null,
    submittedBy: 'Dr. Imran Hossain',
    submittedAt: '2026-06-28T19:12:00Z',
    ai: {
      summary:
        'Possible dengue cluster detected in Sector 7 Lane 9. Standing water and clustered febrile illness fit outbreak profile; immediate vector-control and medical outreach recommended.',
      category: 'Health',
      severity: 'critical',
      sentiment: 'negative',
      confidence: 0.88,
      keywords: ['dengue', 'fever', 'standing water', 'cluster'],
      entities: {
        locations: ['Sector 7', 'Lane 9'],
        people: [],
        organizations: ['City Health Office'],
      },
      recommendations: [
        'Trigger vector-control team for fogging and larvicide.',
        'Send mobile medical unit for free testing.',
        'Issue public advisory for Lane 9 residents.',
      ],
    },
  },
  {
    id: 'RPT-1003',
    title: 'Illegal dumping near riverside',
    description:
      'Construction debris dumped on the east bank of the river over the past week. Approx 4 cubic meters visible from the footbridge.',
    category: 'Environment',
    severity: 'medium',
    status: 'pending',
    location: 'East Riverbank',
    hasImage: true,
    imageUrl: null,
    submittedBy: 'Local Volunteer',
    submittedAt: '2026-06-27T14:02:00Z',
    ai: {
      summary:
        'Active illegal dumping of construction debris on the east riverbank. Environmental contamination risk; cleanup and enforcement recommended.',
      category: 'Environment',
      severity: 'medium',
      sentiment: 'negative',
      confidence: 0.84,
      keywords: ['dumping', 'construction debris', 'riverbank'],
      entities: {
        locations: ['East Riverbank'],
        people: [],
        organizations: [],
      },
      recommendations: [
        'Coordinate cleanup crew with environment department.',
        'Install temporary CCTV at access point.',
        'Issue notice to nearby construction sites.',
      ],
    },
  },
  {
    id: 'RPT-1004',
    title: 'Streetlight outage on main avenue',
    description:
      'Seven consecutive streetlights on Main Avenue between plot 12 and plot 20 are non-functional at night. Pedestrian safety concern.',
    category: 'Infrastructure',
    severity: 'low',
    status: 'resolved',
    location: 'Main Avenue, plots 12-20',
    hasImage: false,
    imageUrl: null,
    submittedBy: 'Community Watch',
    submittedAt: '2026-06-25T22:40:00Z',
    ai: {
      summary:
        'Series of streetlights out along Main Avenue. Low severity but notable safety risk after dark; routine maintenance fix.',
      category: 'Infrastructure',
      severity: 'low',
      sentiment: 'neutral',
      confidence: 0.79,
      keywords: ['streetlight', 'outage', 'main avenue'],
      entities: {
        locations: ['Main Avenue'],
        people: [],
        organizations: [],
      },
      recommendations: [
        'Replace bulbs / fuses along Main Avenue.',
        'Inspect wiring for water ingress.',
      ],
    },
  },
  {
    id: 'RPT-1005',
    title: 'Water supply disruption in Sector 2',
    description:
      'No municipal water supply since yesterday evening in Sector 2. Residents depending on bottled water; pressure in upper floors is zero.',
    category: 'Utilities',
    severity: 'high',
    status: 'in_review',
    location: 'Sector 2',
    hasImage: false,
    imageUrl: null,
    submittedBy: 'Resident Association',
    submittedAt: '2026-06-30T08:15:00Z',
    ai: {
      summary:
        'Sustained water supply failure in Sector 2 likely due to mainline issue. High severity given public health dependency.',
      category: 'Utilities',
      severity: 'high',
      sentiment: 'negative',
      confidence: 0.86,
      keywords: ['water supply', 'disruption', 'sector 2'],
      entities: {
        locations: ['Sector 2'],
        people: [],
        organizations: ['Water Utility Board'],
      },
      recommendations: [
        'Deploy water tanker to Sector 2.',
        'Inspect mainline for breakage.',
        'Issue public schedule for restoration.',
      ],
    },
  },
  {
    id: 'RPT-1006',
    title: 'Suspicious activity near warehouse',
    description:
      'Two individuals observed attempting to cut perimeter fence of warehouse at 02:30. They fled when headlights approached.',
    category: 'Security',
    severity: 'high',
    status: 'action_required',
    location: 'Warehouse District, Gate 3',
    hasImage: false,
    imageUrl: null,
    submittedBy: 'Night Patrol',
    submittedAt: '2026-06-30T02:45:00Z',
    ai: {
      summary:
        'Attempted perimeter breach at warehouse Gate 3 around 02:30. High severity; recommend reviewing CCTV and increasing patrol frequency.',
      category: 'Security',
      severity: 'high',
      sentiment: 'negative',
      confidence: 0.82,
      keywords: ['suspicious', 'perimeter', 'warehouse', 'night'],
      entities: {
        locations: ['Warehouse District', 'Gate 3'],
        people: [],
        organizations: [],
      },
      recommendations: [
        'Pull CCTV footage for 02:00-03:00 window.',
        'Increase patrol frequency for 7 nights.',
        'Brief security vendor on incident.',
      ],
    },
  },
  {
    id: 'RPT-1007',
    title: 'Pothole cluster on service road',
    description:
      'Three large potholes developed on the service road between roundabouts 2 and 3 after recent rain. Two near-miss incidents reported.',
    category: 'Infrastructure',
    severity: 'medium',
    status: 'pending',
    location: 'Service Road R2-R3',
    hasImage: true,
    imageUrl: null,
    submittedBy: 'Daily Commuter',
    submittedAt: '2026-06-26T07:20:00Z',
    ai: {
      summary:
        'Pothole cluster on service road R2-R3 poses vehicle damage and accident risk. Medium severity; routine resurfacing fix recommended.',
      category: 'Infrastructure',
      severity: 'medium',
      sentiment: 'negative',
      confidence: 0.8,
      keywords: ['pothole', 'service road', 'rain'],
      entities: {
        locations: ['Service Road R2-R3'],
        people: [],
        organizations: [],
      },
      recommendations: [
        'Place temporary warning signs.',
        'Schedule resurfacing within 7 days.',
      ],
    },
  },
  {
    id: 'RPT-1008',
    title: 'Medical camp request from elderly group',
    description:
      'Local senior citizens association requesting a free medical camp next weekend. Approx 60 expected attendees, mostly chronic conditions.',
    category: 'Health',
    severity: 'low',
    status: 'pending',
    location: 'Community Hall A',
    hasImage: false,
    imageUrl: null,
    submittedBy: 'Senior Association',
    submittedAt: '2026-06-24T11:00:00Z',
    ai: {
      summary:
        'Routine medical camp request from senior citizens association. Low severity; positive community sentiment.',
      category: 'Health',
      severity: 'low',
      sentiment: 'positive',
      confidence: 0.75,
      keywords: ['medical camp', 'senior citizens', 'community'],
      entities: {
        locations: ['Community Hall A'],
        people: [],
        organizations: ['Senior Citizens Association'],
      },
      recommendations: [
        'Coordinate with city health office for camp logistics.',
        'Allocate 2 doctors and 1 nurse.',
      ],
    },
  },
];

export default SAMPLE_REPORTS;

// --- Mock analytics aggregation -----------------------------------------

export function buildDashboardStats(reports = SAMPLE_REPORTS) {
  const total = reports.length;
  const bySeverity = SEVERITY_LEVELS.reduce((acc, level) => {
    acc[level] = reports.filter((r) => r.ai.severity === level).length;
    return acc;
  }, {});
  const byCategory = REPORT_CATEGORIES.reduce((acc, cat) => {
    acc[cat] = reports.filter((r) => r.ai.category === cat).length;
    return acc;
  }, {});

  const actionRequired = reports.filter(
    (r) => r.status === 'action_required' || r.ai.severity === 'critical',
  ).length;
  const resolved = reports.filter((r) => r.status === 'resolved').length;
  const avgConfidence =
    total > 0
      ? Math.round(
          (reports.reduce((s, r) => s + (r.ai.confidence || 0), 0) / total) *
            100,
        )
      : 0;

  return {
    total,
    bySeverity,
    byCategory,
    actionRequired,
    resolved,
    avgConfidence,
  };
}

// --- Latency simulator ---------------------------------------------------

export function simulateLatency(ms = 350) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}